---
- name: Provision ved.stage vms
  hosts: localhost
  gather_facts: false
  
  roles:
    - ansible-role-mws
  
  vars:
    mws_project: "ved"
    mws_zone: "ru-central1-a"
    mws_default_boot_disk_image: "compute/projects/mws-ubuntu/images/mws-ubuntu-2404-lts-v20250529"

    mws_compute_vm_ssh_username: "cryptouser"
    mws_compute_vm_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYgFG1vVtx5I284w0GvXNchEDkeA5G7UBYe5E1LbqLt nbrener@mts.ru"
    mws_compute_vm_sudo: 'ALL=(ALL) NOPASSWD:ALL'

    mws_default_network_name: "stage-net"

    networks:
      - name: "{{ mws_default_network_name }}"
        internet_access: true
    
    subnets:
      - name: "stage-dmz-subnet"
        cidr: "10.1.1.0/24"

      - name: "stage-private-subnet"
        cidr: "10.1.2.0/24"

      - name: "stage-dbms-subnet"
        cidr: "10.1.3.0/24"
    
    external_static_addresses:
      - name: "stage-vpn-public-address"

    private_static_addresses:
      - name: "stage-vpn-private-address"
        subnet: "stage-dmz-subnet"
    
    firewall_rules:
      - name: "stage-vpn-rule"
        description: "description"
        display_name: "stage-vpn-rule"
        action: "ALLOW"
        direction: "INGRESS"
        proto_ports:
        # SSH
          - "TCP:35532"
        # WireGuard
          - "UDP:51820"
        priority: 1000
        source:
          cidrs: ["0.0.0.0/0"]
        destination:
          cidrs: ["private_address:stage-vpn-private-address/32"]

    vms:
      - name: "stage-vpn"
        network_interfaces:
          - name: enp2s0
            private_static_address_name: "stage-vpn-private-address"
            primary: true
            external_static_address_name: "stage-vpn-public-address"
        boot_disk:
          iops: 1000
          size: "10GB"

      - name: "stage-k8sm-01"
        network_interfaces:
          - name: enp2s0
            subnet: "stage-private-subnet"
            primary: true
        boot_disk:
          iops: 1000
          size: "10GB"

      - name: "stage-k8sm-02"
        network_interfaces:
          - name: enp2s0
            subnet: "stage-private-subnet"
            primary: true
        boot_disk:
          iops: 1000
          size: "10GB"

      - name: "stage-k8sm-03"
        network_interfaces:
          - name: enp2s0
            subnet: "stage-private-subnet"
            primary: true
        boot_disk:
          iops: 1000
          size: "10GB"

      - name: "stage-k8sw-01"
        #vm_type: "vmTypes/gen-8-16"
        vm_type: "vmTypes/gen-2-4"
        network_interfaces:
          - name: enp2s0
            subnet: "stage-private-subnet"
            primary: true
        boot_disk:
          iops: 1000
          size: "30GB"

      - name: "stage-k8sw-02"
        #vm_type: "vmTypes/gen-8-16"
        vm_type: "vmTypes/gen-2-4"
        network_interfaces:
          - name: enp2s0
            subnet: "stage-private-subnet"
            primary: true
        boot_disk:
          iops: 1000
          size: "30GB"

      - name: "stage-k8sw-03"
        #vm_type: "vmTypes/gen-8-16"
        vm_type: "vmTypes/gen-2-4"
        network_interfaces:
          - name: enp2s0
            subnet: "stage-private-subnet"
            primary: true
        boot_disk:
          iops: 1000
          size: "30GB"
